import type { Hero, Map, SetInfo } from './types'

import AzuchiCastle from '@/assets/images/maps/Azuchi_Castle.webp'
import BaskervilleManor from '@/assets/images/maps/Baskerville_Manor.webp'
import FayrlundForest from '@/assets/images/maps/Fayrlund_Forest.webp'
import GlobeTheater from '@/assets/images/maps/Globe_Theater.webp'
import HangingGardens from '@/assets/images/maps/Hanging_Gardens.webp'
import Helicarrier from '@/assets/images/maps/Helicarrier.webp'
import HellsKitchenMap from "@/assets/images/maps/Hell's_Kitchen.webp"
import Heorot from '@/assets/images/maps/Heorot.webp'
import KaerMorhen from '@/assets/images/maps/Kaer_Morhen.webp'
import KingSolomonsMine from "@/assets/images/maps/King_Solomon's_Mine.webp"
import Marmoreal from '@/assets/images/maps/Marmoreal.webp'
import McMinnvilleOR from '@/assets/images/maps/McMinnville_OR.webp'
import Naglfar from '@/assets/images/maps/Naglfar.webp'
import NavyPier from '@/assets/images/maps/Navy_Pier.webp'
import PointPleasant from '@/assets/images/maps/Point_Pleasant.webp'
import RaptorPaddock from '@/assets/images/maps/Raptor_Paddock.webp'
import SanctumSantorum from '@/assets/images/maps/Sanctum_Santorum.webp'
import Sarpedon from '@/assets/images/maps/Sarpedon.webp'
import SherwoodForest from '@/assets/images/maps/Sherwood_Forest.webp'
import Soho from '@/assets/images/maps/Soho.webp'
import StreetsOfNovigrad from '@/assets/images/maps/Streets_of_Novigrad.webp'
import SunnydaleHigh from '@/assets/images/maps/Sunnydale_High.webp'
import TheBronze from '@/assets/images/maps/The_Bronze.webp'
import TheRaft from '@/assets/images/maps/The_Raft.webp'
import TRexPaddock from '@/assets/images/maps/T_Rex_Paddock.webp'
import Yukon from '@/assets/images/maps/Yukon.webp'

export const UNMATCHED_SETS: SetInfo[] = [
  { name: 'Battle of Legends, Volume One', franchise: 'Unmatched' },
  { name: 'Battle of Legends, Volume Two', franchise: 'Unmatched' },
  { name: 'Battle of Legends, Volume Three', franchise: 'Unmatched' },
  { name: 'Bruce Lee', franchise: 'Unmatched' },
  { name: 'Robin Hood vs Bigfoot', franchise: 'Unmatched' },
  { name: 'Cobble & Fog', franchise: 'Unmatched' },
  { name: 'Little Red Riding Hood vs. Beowulf', franchise: 'Unmatched' },
  { name: 'Houdini vs. The Genie', franchise: 'Unmatched' },
  { name: 'Adventures: Tales to Amaze', franchise: 'Unmatched' },
  { name: 'Sun\'s Origin', franchise: 'Unmatched' },
  { name: 'Slings & Arrows', franchise: 'Unmatched' },
  { name: 'Muhammad Ali vs. Bruce Lee', franchise: 'Unmatched' },
  { name: 'Jurassic Park – InGen vs. Raptors', franchise: 'Jurassic Park' },
  { name: 'Jurassic Park – Sattler vs. T‑Rex', franchise: 'Jurassic Park' },
  { name: 'Buffy the Vampire Slayer', franchise: 'Buffy' },
  { name: 'Deadpool', franchise: 'Marvel' },
  { name: 'Redemption Row', franchise: 'Marvel' },
  { name: 'Hell\'s Kitchen', franchise: 'Marvel' },
  { name: 'Teen Spirit', franchise: 'Marvel' },
  { name: 'For King and Country', franchise: 'Marvel' },
  { name: 'Brains and Brawn', franchise: 'Marvel' },
  { name: 'The Witcher – Realms Fall', franchise: 'The Witcher' },
  { name: 'The Witcher – Steel & Silver', franchise: 'The Witcher' },
  { name: 'Unmatched Adventures: Teenage Mutant Ninja Turtles', franchise: 'TMNT' },
  { name: 'TMNT: Shredder and Krang', franchise: 'TMNT' },
]

export const FRANCHISES = Array.from(new Set(UNMATCHED_SETS.map(s => s.franchise))).sort()

export function getSetsByFranchise(franchise: string): SetInfo[] {
  return UNMATCHED_SETS.filter(s => s.franchise === franchise)
}

export const HEROES: Hero[] = [
  { id: 'achilles', name: 'Achilles', hp: 18, move: 2, attack: 'MELEE', set: 'Battle of Legends, Volume Two', sidekicks: [{ name: 'Patroclus', count: 1, hp: 6, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/9lCDpWINK-hNBFjVYHtWPQ__imagepage/img/o9mApjJmLmVT0Kw5fwBPZBmxcS0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257613.png', abilityDescription: "When Patroclus is defeated, discard 2 random cards. While Patroclus is defeated: (1) Add +2 to the value of all Achilles' attacks. (2) If Achilles wins combat, draw 1 card." },
  { id: 'alice', name: 'Alice', hp: 13, move: 2, attack: 'MELEE', set: 'Battle of Legends, Volume One', sidekicks: [{ name: 'The Jabberwock', count: 1, hp: 8, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/A_FZwxPy_JcKa1ZjEtlmqQ__imagepage/img/l-WrDtPbLIOxqOHv-VX6u5OgKVU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5609969.png', abilityDescription: "When you place Alice, choose whether she starts the game BIG or SMALL. When Alice is BIG, add 2 to the value of her attack cards. When Alice is SMALL, add 1 to the value of her defense cards." },
  { id: 'ancient-leshen', name: 'Ancient Leshen', hp: 13, move: 1, attack: 'RANGED', set: 'The Witcher – Steel & Silver', sidekicks: [{ name: 'Wolves', count: 2, hp: 1, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/VFbI8rCPBG-qp39Px8QhGQ__imagepage/img/8oI5VuFdqj0i4rI_olB_QJ18mL4=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7775202.png', abilityTitle: "HEART OF THE FOREST", abilityDescription: "Add +3 to the value of the Leshen's attacks if it already attacked this turn. Your Wolves have a move value of 3." },
  { id: 'angel', name: 'Angel', hp: 16, move: 2, attack: 'MELEE', set: 'Buffy the Vampire Slayer', sidekicks: [{ name: 'Faith', count: 1, hp: 9, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/TRbkJxvY2nPHHKF77n9lFw__imagepage/img/jkLG7RQOoTmb4S7w0fRlwV9c_a8=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093881.png', abilityDescription: "After Angel or Faith attacks, if you lost the combat, draw 1 card." },
  { id: 'annie-christmas', name: 'Annie Christmas', hp: 14, move: 2, attack: 'MELEE', set: 'Adventures: Tales to Amaze', sidekicks: [{ name: 'Charlie', count: 1, hp: 8, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/VfE1UIPxxgvnTwz7wHM7pA__imagepage/img/EWp-DqLb7wP6MfDjX-wX90BmZ_w=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257631.png', abilityTitle: "NECKLACE OF PEARLS", abilityDescription: "Add +2 to the value of Annie's attacks if she has less health than the defender." },
  { id: 'beowulf', name: 'Beowulf', hp: 17, move: 2, attack: 'MELEE', set: 'Little Red Riding Hood vs. Beowulf', sidekicks: [{ name: 'Wiglaf', count: 1, hp: 9, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/tQDdF0rQ1q_LTfhqrxS8hg__imagepage/img/bN-NFXR4gB5qakWp1X_4_hD5OQM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5182948.png', abilityDescription: "Beowulf starts with 1 Rage. When Beowulf is dealt damage, he gains 1 Rage. Beowulf has a maximum of 3 rage." },
  { id: 'bigfoot', name: 'Bigfoot', hp: 16, move: 3, attack: 'MELEE', set: 'Robin Hood vs Bigfoot', sidekicks: [{ name: 'The Jackalope', count: 1, hp: 6, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/RJ_Kfkql9XWw6y3uxlOSpw__imagepage/img/dUZYt8uy8SJHg6d1xDwJDdHQaYc=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4830607.png', abilityDescription: "At the end of your turn, if there are no opposing fighters in Bigfoot's zone, you may draw 1 card." },
  { id: 'black-panther', name: 'Black Panther', hp: 14, move: 2, attack: 'MELEE', set: 'For King and Country', sidekicks: [{ name: 'Shuri', count: 1, hp: 6, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/e5_zzmNTdJgj79m9vM65bw__imagepage/img/zz6z_1PMl-3vMSPj7V3jGPCEF5c=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093923.png', abilityTitle: "VIBRANIUM SUIT", abilityDescription: "Whenever you BOOST, draw 1 card. Cards stored in your VIBRANIUM SUIT can only be used to BOOST." },
  { id: 'black-widow', name: 'Black Widow', hp: 13, move: 2, attack: 'RANGED', set: 'For King and Country', sidekicks: [{ name: 'Maria Hill', count: 1, hp: 6, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/yqwfk1-Uz3_NZ1L_kwDVSg__imagepage/img/s4oQMVpBR5Z02xjAxCvB4vukrzM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093929.png', abilityTitle: "MISSION READY", abilityDescription: 'Before drawing your starting hand, add "The Moscow Protocol" card to your hand. Then shuffle your deck and draw 5 cards. (Your starting hand is 6 cards instead of 5.)' },
  { id: 'bloody-mary', name: 'Bloody Mary', hp: 16, move: 3, attack: 'MELEE', set: 'Battle of Legends, Volume Two', imageUrl: 'https://cf.geekdo-images.com/a4QqpTTDZvvfyaQmYMdVPg__imagepage/img/sppaxf0Lh1oqvK73_xgNiU_0Gzg=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257617.png', abilityDescription: "At the start of your turn, if you have exactly 3 cards in hand, gain 1 action." },
  { id: 'bruce-lee', name: 'Bruce Lee', hp: 14, move: 3, attack: 'MELEE', set: 'Bruce Lee', imageUrl: 'https://cf.geekdo-images.com/VDiIXjVILnXMQNDO8IVlNg__imagepage/img/Sb8H3_lZhE98-i7yStUTWvZLhWk=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5182990.png', abilityTitle: "FLEET OF FOOT", abilityDescription: "At the end of your turn, you may move Bruce Lee 1 space." },
  { id: 'buffy', name: 'Buffy', hp: 14, move: 3, attack: 'MELEE', set: 'Buffy the Vampire Slayer', sidekicks: [{ name: 'Giles', count: 1, hp: 6, attack: 'MELEE' }, { name: 'Xander', count: 1, hp: 6, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/OKLFzqoWIc0eU-lMb7nkFA__imagepage/img/L-iLYj6r54FQpkEKKNq8Xvuii04=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093883.png', abilityDescription: "Buffy may move through spaces containing opposing fighters (including when she is moved by effects)." },
  { id: 'bullseye', name: 'Bullseye', hp: 14, move: 2, attack: 'RANGED', set: 'Hell\'s Kitchen', imageUrl: 'https://cf.geekdo-images.com/l-0GBzfSJdLRvCq-s3ZyLw__imagepage/img/6lrQ1iXzCuXsFZxJ14EGQ5nH1cI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093939.png', abilityDescription: "Bullseye can attack from up to 5 spaces away (ignoring zones)." },
  { id: 'ciri', name: 'Ciri', hp: 15, move: 2, attack: 'MELEE', set: 'The Witcher – Steel & Silver', sidekicks: [{ name: 'Ihuarraquax', count: 1, hp: 7, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/Nw7IM6HrJJCjjJLXdsgL2g__imagepage/img/Ql1-j0DJqJWAyQDH9HEXlUdVVoM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7775204.png', abilityTitle: "UNCONTAINABLE POWER", abilityDescription: "If you have 7 or more Source cards in your discard pile, effects on Ciri's cards cannot be canceled." },
  { id: 'cloak-dagger', name: 'Cloak & Dagger', hp: 8, move: 2, attack: 'MELEE', set: 'Teen Spirit', sidekicks: [{ name: 'Dagger', count: 1, hp: 8, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/U8BJ0y6Y5YYY2djFNW9YsA__imagepage/img/dMgkuZBmkfWawFyqJG_GKWS0RDs=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093933.png', abilityTitle: "UMBRA / REFRACTION", abilityDescription: "UMBRA: After you attack, if Cloak dealt at least 2 combat damage, your opponent discards 1 card. REFRACTION: After you attack, if Dagger dealt at least 2 combat damage, gain 1 action." },
  { id: 'daredevil', name: 'Daredevil', hp: 17, move: 3, attack: 'MELEE', set: 'Hell\'s Kitchen', imageUrl: 'https://cf.geekdo-images.com/8SDHh8UW-hXDNyAdRfxq3g__imagepage/img/Q03PvKt4NL7o20FYLlUZxbXlWkc=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093943.png', abilityDescription: "DURING COMBAT: If you have 2 or fewer cards in your hand, you may BLIND BOOST your attack or defense. (If you have other DURING COMBAT effects, choose the order.)" },
  { id: 'deadpool', name: 'Deadpool', hp: 10, move: 2, attack: 'MELEE', set: 'Deadpool', imageUrl: 'https://cf.geekdo-images.com/vRz80UWDlhb8QaGzQgmqeA__imagepage/img/hgXSt45_XQDpmtJiJ1u25EZj-Ag=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093937.png', abilityDescription: "After you attack, Deadpool recovers 1 health. Also, if your opponent's real name is Logan, all your attacks are +5." },
  { id: 'doctor-strange', name: 'Doctor Strange', hp: 14, move: 2, attack: 'RANGED', set: 'Brains and Brawn', sidekicks: [{ name: 'Wong', count: 1, hp: 6, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/fKC-e_cZ1q5VG_X2qP0f1g__imagepage/img/RgEXKdO1uBJ4ygXQQ4eMSU7k0w8=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093945.png', abilityTitle: "DARK PACT", abilityDescription: "After each combat, if Doctor Strange played a card, you may deal 1 damage to him. If you do, put that card on the bottom of your deck and draw 1 card." },
  { id: 'dr-ellie-sattler', name: 'Dr. Sattler', hp: 13, move: 2, attack: 'MELEE', set: 'Jurassic Park – Sattler vs. T‑Rex', sidekicks: [{ name: 'Dr. Malcolm', count: 1, hp: 7, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/EX2lnBZajdWaYW_NR7GsWQ__imagepage/img/rGfE7rJbR8wlkxzKaJbLsO8UBkc=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5652029.png', abilityDescription: "After Dr. Sattler or Dr. Malcolm move, place an insight token in their new space. You have 5 insight tokens." },
  { id: 'dr-jill-trent', name: 'Dr. Jill Trent', hp: 13, move: 2, attack: 'MELEE', set: 'Adventures: Tales to Amaze', sidekicks: [{ name: 'Daisy', count: 1, hp: 6, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/Ppa3hELSoxjUNpwQrTIUTQ__imagepage/img/a59fvIf3l_YhZ5kZgFzYz9GqDMg=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257636.png', abilityTitle: "GADGETOLOGY", abilityDescription: "At the start of your turn, activate one of your gadgets. Whenever Jill Trent attacks, resolve the active gadget's effect." },
  { id: 'medusa', name: 'Medusa', hp: 16, move: 3, attack: 'RANGED', set: 'Battle of Legends, Volume One', sidekicks: [{ name: 'Harpies', count: 3, hp: 2, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/T-A4wGqLFywPYo2WgIj6Tg__imagepage/img/N_D8_OFSbT6BNbXuFnuxu_2AiE4=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5609982.png', abilityDescription: "At the start of your turn, you may deal 1 damage to an opposing fighter in Medusa's zone." },
  { id: 'king-arthur', name: 'King Arthur', hp: 18, move: 2, attack: 'MELEE', set: 'Battle of Legends, Volume One', sidekicks: [{ name: 'Merlin', count: 1, hp: 6, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/6VoqcPdHxKNu2wQEbIr3GA__imagepage/img/X-YQJieCsE7Jn-RGIEELyRTzEag=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5609977.png', abilityDescription: "When King Arthur attacks, you may BOOST that attack. Play the BOOST card, face down, along with your attack card. If your opponent cancels the effects on your attack card, the BOOST is discarded without effect." },
  { id: 'sinbad', name: 'Sinbad', hp: 15, move: 2, attack: 'MELEE', set: 'Battle of Legends, Volume One', sidekicks: [{ name: 'The Porter', count: 1, hp: 6, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/7hKRE5V_3gVRtcbcWB3Ucw__imagepage/img/v68q5IZCGtYVZk6A9BmP1bN4lj4=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5609986.png', abilityDescription: "When you maneuver, you may move your fighters +1 space for each Voyage card in your discard pile." },
  { id: 'robin-hood', name: 'Robin Hood', hp: 13, move: 2, attack: 'RANGED', set: 'Robin Hood vs Bigfoot', sidekicks: [{ name: 'Outlaws', count: 4, hp: 1, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/Y3lCu-ZE4VZ6sBZw_W4-Gw__imagepage/img/rvXYSvM2cqCWzGxBnYJ0n7kvjvI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4830611.png', abilityDescription: "After you attack, you may move your attacking fighter up to 2 spaces." },
  { id: 'ingen', name: 'Robert Muldoon', hp: 14, move: 3, attack: 'RANGED', set: 'Jurassic Park – InGen vs. Raptors', sidekicks: [{ name: 'Ingen Workers', count: 3, hp: 2, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/8zf7IKj82FQB1t-nnGOV4A__imagepage/img/lzYNLMVVrW4UtzCz1QWbYUGpRoo=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5652033.png', abilityDescription: "At the start of your turn, you may place a trap. Whenever one of your traps is returned to the box, draw a card. Muldoon starts with 8 traps." },
  { id: 'raptors', name: 'Raptors', hp: 7, move: 3, attack: 'MELEE', set: 'Jurassic Park – InGen vs. Raptors', sidekicks: [{ name: 'Raptors', count: 2, hp: 7, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/O_lwZmJN-3sWx-oyhDw0rA__imagepage/img/fgINTPPc-u7kGFjXvKnTpK5c22o=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5652035.png', abilityDescription: "Raptors add 1 to the value of their attack cards for each of your other Raptors adjacent to the defender." },
  { id: 'sherlock-holmes', name: 'Sherlock Holmes', hp: 16, move: 2, attack: 'MELEE', set: 'Cobble & Fog', sidekicks: [{ name: 'Dr. Watson', count: 1, hp: 8, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/IqIEU9H73W8p5Pzbe1vprA__imagepage/img/q4bBVeVlC-YVhaNGf0J2RO0XbXo=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5182960.png', abilityDescription: "Effects on HOLMES and DR. WATSON cards cannot be canceled by an opponent. (Effects on ANY cards can be canceled.)" },
  { id: 'dracula', name: 'Dracula', hp: 13, move: 2, attack: 'MELEE', set: 'Cobble & Fog', sidekicks: [{ name: 'The Sisters', count: 3, hp: 1, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/uj-PHVY0R0SL6SbJzm8t6Q__imagepage/img/HI2LYtzjkIkCy2TGx1HjRfxRvsc=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5182952.png', abilityDescription: "At the start of your turn, you may deal 1 damage to a fighter adjacent to Dracula. If you do, draw a card." },
  { id: 'jekyll-hyde', name: 'Jekyll & Hyde', hp: 16, move: 2, attack: 'MELEE', set: 'Cobble & Fog', imageUrl: 'https://cf.geekdo-images.com/uu3Dsp-ztHNJbhajKxPovA__imagepage/img/BAdkTbhqCwmHcxHPdBY1iVGVjT4=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5182956.png', abilityDescription: "Start the game as Dr. Jekyll. At the start of your turn, you may transform into Dr. Jekyll or Mr. Hyde. Use the transformation token to indicate what he currently is. While Mr. Hyde: After you Maneuver, take 1 damage." },
  { id: 'invisible-man', name: 'Invisible Man', hp: 15, move: 2, attack: 'MELEE', set: 'Cobble & Fog', imageUrl: 'https://cf.geekdo-images.com/j_FqTXrqnJqfBHlqjhN9Ug__imagepage/img/jKCy66D5h4G5mLXl-oCfVDo0SQE=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5182954.png', abilityDescription: "At the start of the game, after you place Invisible Man, place 3 fog tokens in separate spaces in his zone. When Invisible Man is on a space with a fog token, add 1 to the value of his defense cards. Invisible Man may move between two spaces with fog tokens as if they were adjacent." },
  { id: 'spike', name: 'Spike', hp: 15, move: 2, attack: 'MELEE', set: 'Buffy the Vampire Slayer', sidekicks: [{ name: 'Drusilla', count: 1, hp: 7, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/VxQo_ZywuMJ4EWBAtc6zQA__imagepage/img/7F-9c7fKIUF1vKo-YrQ5LOxBvtg=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093889.png', abilityDescription: "At the start of your turn, you may place a Shadow token in any space adjacent to Spike or Drusilla." },
  { id: 'willow', name: 'Willow', hp: 14, move: 2, attack: 'RANGED', set: 'Buffy the Vampire Slayer', sidekicks: [{ name: 'Tara', count: 1, hp: 6, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/5yfLH_gg7fXj32xKr9_yIQ__imagepage/img/a7mjF-7fCLRAqKRADHVNDYJV0ng=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093893.png', abilityDescription: "When Willow or Tara is dealt damage, Willow becomes Dark Willow. At the end of your turn, if Dark Willow is adjacent to Tara, she becomes Willow." },
  { id: 'little-red', name: 'Little Red Riding Hood', hp: 14, move: 2, attack: 'MELEE', set: 'Little Red Riding Hood vs. Beowulf', sidekicks: [{ name: 'Huntsman', count: 1, hp: 9, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/RrFKdcJ9fPcF0u5e4KNB8A__imagepage/img/03iTVLt7mDYVUYIhfZ49x51F0Fo=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5182974.png', abilityDescription: "Resolve an effect on a card you play if the symbol next to the effect matches the item in your basket. At the start of the game, place \"Little Red's Basket\" in your discard pile. Little Red's Basket: This starts in your discard pile. It does not count as a card." },
  { id: 'sun-wukong', name: 'Sun Wukong', hp: 17, move: 2, attack: 'MELEE', set: 'Battle of Legends, Volume Two', sidekicks: [{ name: 'Clones', count: 3, hp: 2, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/OkGx7fXRrF_-l7BPZ6_e_A__imagepage/img/KH2ixWxYaV-5TLfJ_CBQGDVL7jw=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257625.png', abilityDescription: "At the start of your turn, you may take 1 damage to summon a Clone in an empty space adjacent to Sun Wukong. Do not start with any Clones on the board." },
  { id: 'yennenga', name: 'Yennenga', hp: 15, move: 2, attack: 'RANGED', set: 'Battle of Legends, Volume Two', sidekicks: [{ name: 'Archers', count: 2, hp: 2, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/NqnlJR48tDFVqcUAe5wKWw__imagepage/img/S9p-9fqbFbbApF0v0lK-uNvP-rU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257627.png', abilityDescription: "If Yennenga would take damage, you may assign any amount of that damage to one or more Archers in her zone instead. (You may not assign more damage to an Archer than their remaining health.)" },
  { id: 'blackbeard', name: 'Blackbeard', hp: 16, move: 2, attack: 'RANGED', set: 'Battle of Legends, Volume Three', imageUrl: 'https://cf.geekdo-images.com/JC3qcyUIBEq8XKuN6bx1zw__imagepage/img/iQEuJ3JWMzikYyq2bFXQvCpYqnU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7759172.png', abilityTitle: "PRIVATEER TURNED PIRATE", abilityDescription: "Start the game with 1 doubloon in the treasury, you have the other 2. ● At the start of your turn, you may pay 1 doubloon to gain 1 action. ● When Blackbeard takes combat damage, pay 1 doubloon." },
  { id: 'chupacabra', name: 'Chupacabra', hp: 13, move: 3, attack: 'MELEE', set: 'Battle of Legends, Volume Three', imageUrl: 'https://cf.geekdo-images.com/lhPVSDWyEvZQhFFjuTDxmQ__imagepage/img/PjRJjQvI7_zPQA1noBHk4hDIv1Q=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7759175.png', abilityTitle: "THE HUNGER", abilityDescription: "After you attack, you may draw a card." },
  { id: 'loki', name: 'Loki', hp: 14, move: 2, attack: 'RANGED', set: 'Battle of Legends, Volume Three', imageUrl: 'https://cf.geekdo-images.com/LDOIVNy5dHmxL96Bvq4Hag__imagepage/img/nEPuhXCWE8xHiBNRJ4zJXg5aI4w=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7759181.png', abilityTitle: "MISCHIEF-MONGER", abilityDescription: "After you play a TRICK, put that card into your opponent's hand instead of your discard pile. If an opponent discards a TRICK from their hand, return that card to your hand or the top of your deck. Add +1 to your move value for each TRICK in your opponents' hands." },
  { id: 'pandora', name: 'Pandora', hp: 13, move: 2, attack: 'RANGED', set: 'Battle of Legends, Volume Three', sidekicks: [{ name: 'Kakodæmons', count: 3, hp: 1, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/p_ynSGJhOg6y6Qjv6LqJtQ__imagepage/img/cY5hYoKSfOgYIEuqCUG_HdqU2ig=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7759183.png', abilityTitle: "PANDORA'S BOX", abilityDescription: "Do not start with any Kakodæmons on the board. At the start of your turn, open Pandora's Box. Pandora's Box is a deck of seven cards called MISERIES. When you open Pandora's Box, reveal the top card and resolve its effect (if any). You may keep revealing and resolving additional cards, one at a time, until you choose to stop. If there are three or more total feathers on revealed cards, you must stop revealing, then Pandora takes 1 damage for each revealed MISERY. At the end of your turn, shuffle all revealed MISERIES back into Pandora's Box." },
  { id: 'luke-cage', name: 'Luke Cage', hp: 13, move: 2, attack: 'MELEE', set: 'Redemption Row', sidekicks: [{ name: 'Misty Knight', count: 1, hp: 6, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/vPtSEYtO2mjsjFCNsHRbtw__imagepage/img/90Q4pSz3Hxa0JPB48A_eNpfF6V4=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093967.png', abilityDescription: "Luke Cage takes 2 less combat damage from attacks. (When defending, Luke Cage wins combat if he takes no damage, even if he didn't play a card.)" },
  { id: 'moon-knight', name: 'Moon Knight', hp: 16, move: 3, attack: 'MELEE', set: 'Redemption Row', imageUrl: 'https://cf.geekdo-images.com/Lp_RLz1S6GbgBm5_NrZiKw__imagepage/img/tXb3zOF88cP7HDBQNY6hEgxYh3U=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093971.png', abilityDescription: "Start the game as Moon Knight. At the end of your turn, change to your next identity (Moon Knight ➞ Khonshu ➞ Mr. Knight ➞ Moon Knight). ● Moon Knight: At the start of your turn, move up to 2 spaces. ● Khonshu: Khonshu adds +2 to the value of his attack cards. He does not take damage from effects other than combat damage. ● Mr. Knight: Mr. Knight adds +1 to all his defense values." },
  { id: 'ghost-rider', name: 'Ghost Rider', hp: 17, move: 2, attack: 'MELEE', set: 'Redemption Row', imageUrl: 'https://cf.geekdo-images.com/6cPOXsAjQO5lNH7KvzN_WA__imagepage/img/xwGaFqjZsxGC0VB3S3X8EWH4B2A=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093951.png', abilityDescription: "Ghost Rider starts the game with 5 Hellfire. When you maneuver you may spend 1 Hellfire. If you do, increase Ghost Rider's move value to 4, and he may move through opposing fighters. Then deal 1 damage to each opposing fighter he moved through." },
  { id: 'elektra', name: 'Elektra', hp: 7, move: 2, attack: 'MELEE', set: 'Hell\'s Kitchen', sidekicks: [{ name: 'The Hand', count: 4, hp: 1, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/uGqLsF_EtTUdEEyDo4x60A__imagepage/img/lS6Ud6r9cqpNlnQFrU4dHgGUOmY=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093947.png', abilityDescription: "The first time Elektra would be defeated, remove her and all Hand from the board. She is not defeated. At the start of your next turn, Resurrect her. (Ignore effects with the RESURRECTED symbol.) When Elektra Resurrects: Flip your health dial. Shuffle your discard pile into your deck. Place Elektra and all Hand back onto the board with each fighter in a different zone. (You must resolve effects with the RESURRECTED symbol.)" },
  { id: 't-rex', name: 'T. Rex', hp: 27, move: 1, attack: 'MELEE', set: 'Jurassic Park – Sattler vs. T‑Rex', imageUrl: 'https://cf.geekdo-images.com/HUXE5AUDlVd0lVz_YMW5gA__imagepage/img/sL1VBVd_1AH0y6bW2LKh56QZaxg=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5652032.png', abilityDescription: "T. Rex is a large fighter. (She can attack up to 2 spaces away.) At the end of your turn, draw a card." },
  { id: 'houdini', name: 'Harry Houdini', hp: 14, move: 2, attack: 'MELEE', set: 'Houdini vs. The Genie', sidekicks: [{ name: 'Bess', count: 1, hp: 5, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/M6CpbIThDSa5nqCUxOp9yQ__imagepage/img/pRNMiLTJD_aFhWcbLJwKEjHAGGw=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257642.png', abilityTitle: "ESCAPE ARTIST", abilityDescription: "When you take the maneuver action and BOOST, you may place Houdini in any space instead of moving. (Bess moves as normal.)" },
  { id: 'the-genie', name: 'The Genie', hp: 16, move: 3, attack: 'RANGED', set: 'Houdini vs. The Genie', imageUrl: 'https://cf.geekdo-images.com/B7pSMbIz2fVjO85FvkCLKw__imagepage/img/dC4fWYnc5cj4tXKNGdrhWajoCYc=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257644.png', abilityTitle: "INFINITE POWER", abilityDescription: "At the start of your turn, you may discard 1 card to gain 1 action." },
  { id: 'ms-marvel', name: 'Ms. Marvel', hp: 14, move: 2, attack: 'MELEE', set: 'Teen Spirit', imageUrl: 'https://cf.geekdo-images.com/FxSZOk3c7tXHdIhzzkp-9Q__imagepage/img/CyJR_MbXcqkATyREBFRXKrXARoQ=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093979.png', abilityTitle: "STRETCHY", abilityDescription: "At the start of your turn, you may move Ms. Marvel 1 space. Ms. Marvel can attack from up to 2 spaces away (ignoring zones)." },
  { id: 'squirrel-girl', name: 'Squirrel Girl', hp: 13, move: 2, attack: 'MELEE', set: 'Teen Spirit', sidekicks: [{ name: 'Squirrels', count: 4, hp: 1, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/hXPj-jYDZKxWqvjIW-GhGQ__imagepage/img/z_YiJ3tqMgZ7wE0q7pj46dNBNuI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093987.png', abilityTitle: "GO NUTS!", abilityDescription: "At the start of your turn, summon a squirrel in a space adjacent to Squirrel Girl. Squirrels are small fighters. Do not start with any squirrels on the board." },
  { id: 'winter-soldier', name: 'Winter Soldier', hp: 15, move: 2, attack: 'RANGED', set: 'For King and Country', imageUrl: 'https://cf.geekdo-images.com/nF_zLfAL0tDzwLN78IlDgA__imagepage/img/JnZBONLbZF6iEWI8nW3OFn5kdoE=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093991.png', abilityTitle: "BRAINWASHED", abilityDescription: "Effects on Winter Soldier's cards cannot be canceled." },
  { id: 'spider-man', name: 'Spider‑Man', hp: 15, move: 3, attack: 'MELEE', set: 'Brains and Brawn', sidekicks: [{ name: 'Aunt May', count: 1, hp: 5, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/HqSJ6zFyEi4ifnqQHpgOaw__imagepage/img/H7zMM_o3Ee8OJbVD9qNg1Hg1BYk=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093983.png', abilityTitle: "SPIDEY‑SENSE", abilityDescription: "When an opponent attacks Spider‑Man, before you play a defense card, they must tell you the printed value of their card." },
  { id: 'she-hulk', name: 'She‑Hulk', hp: 20, move: 2, attack: 'MELEE', set: 'Brains and Brawn', sidekicks: [{ name: 'Pug', count: 1, hp: 5, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/I9QHsRbN8cRkz-cSjKOkYA__imagepage/img/gXSXVq8jq3sxJlHcHEG6-_5KhqM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6093977.png', abilityTitle: "JUST THROW SOMETHING", abilityDescription: "At the start of your turn, you may discard a card to deal damage equal to its BOOST value to a fighter in your zone." },
  { id: 'nikola-tesla', name: 'Nikola Tesla', hp: 14, move: 2, attack: 'RANGED', set: 'Adventures: Tales to Amaze', sidekicks: [{ name: 'Pigeons', count: 2, hp: 2, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/v8j8U3bvKOuNj72UajZBag__imagepage/img/NujPG15-JCQxRXqHsqb0VljsSO0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257652.png', abilityTitle: "ELECTRICAL OVERFLOW", abilityDescription: "Start the game with 1 coil charged. At the end of your turn, charge 1 coil. At the start of your turn, if both coils are charged, deal 1 damage to each opposing fighter adjacent to Tesla and move them up to 1 space." },
  { id: 'golden-bat', name: 'Golden Bat', hp: 18, move: 3, attack: 'MELEE', set: 'Adventures: Tales to Amaze', imageUrl: 'https://cf.geekdo-images.com/E4iMhN1Lp3gUz_X46_Mkmw__imagepage/img/d6JTIpM0WiQyqLiDivCIqj1qgNo=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257638.png', abilityTitle: "THE FIRST SUPERHERO", abilityDescription: "If you haven't taken a Maneuver action this turn, add +2 to the value of Golden Bat's attacks." },
  { id: 'tomoe-gozen', name: 'Tomoe Gozen', hp: 14, move: 2, attack: 'RANGED', set: 'Sun\'s Origin', imageUrl: 'https://cf.geekdo-images.com/eHGrh8aQdtKNJjg7eYYs8g__imagepage/img/x6cBNs2h2CzLvUxkTW9Oq-8n48M=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257659.png', abilityTitle: "ATTACK OF OPPORTUNITY", abilityDescription: "When an opposing hero leaves Tomoe Gozen's zone, deal 1 damage to that hero." },
  { id: 'oda-nobunaga', name: 'Oda Nobunaga', hp: 13, move: 2, attack: 'MELEE', set: 'Sun\'s Origin', sidekicks: [{ name: 'Honor Guard', count: 2, hp: 2, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/EabM2FdC2WiQKQKECe-5xw__imagepage/img/Dy75XCazBF0vIaU2FHubZJOh6Uw=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257654.png', abilityTitle: "MASTER STRATEGIST", abilityDescription: "Other friendly fighters in Oda Nobunaga's zone add +1 to the value of their played combat cards. (Oda Nobunaga does not benefit from this ability.)" },
  { id: 'hamlet', name: 'Hamlet', hp: 15, move: 2, attack: 'MELEE', set: 'Slings & Arrows', sidekicks: [{ name: 'Rosencrantz', count: 1, hp: 2, attack: 'MELEE' }, { name: 'Guildenstern', count: 1, hp: 2, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/N5WU_kJZpx6cJjlNj7P2iw__imagepage/img/PzXbJDXpALZxsE5gDdGIHiYEAa0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257640.png', abilityTitle: "THE QUESTION", abilityDescription: "At the start of your turn, choose TO BE or NOT TO BE. If you choose NOT TO BE, deal 2 damage to one of your fighters. ● TO BE: When you maneuver, draw 1 additional card. ● NOT TO BE: Add +2 to the value of Hamlet's attacks." },
  { id: 'titania', name: 'Titania', hp: 12, move: 2, attack: 'RANGED', set: 'Slings & Arrows', sidekicks: [{ name: 'Oberon', count: 1, hp: 6, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/BoevOvNBOw2eZFj0u-tJrg__imagepage/img/00eHQOOSNaGWvhNpkr1gmlKmr-4=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257661.png', abilityTitle: "FAIRY MAGIC", abilityDescription: "If you do not have a face‑up glamour at the start of your turn, flip the top card of your glamour deck face‑up. Its effect is ongoing while it remains face‑up." },
  { id: 'wayward-sisters', name: 'The Wayward Sisters', hp: 6, move: 2, attack: 'MELEE', set: 'Slings & Arrows', sidekicks: [{ name: 'The Sisters', count: 1, hp: 6, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/aR1XGWcE_2J4nAvXhD0tig__imagepage/img/Rk9QMk8JxXL20n0MXOUIWIuJh6Q=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257665.png', abilityTitle: "BUBBLING BREW", abilityDescription: "Your cards go into your cauldron instead of your discard pile. After you attack, you may cast one spell that you have the ingredients for. If you do, discard all the cards in your cauldron." },
  { id: 'william-shakespeare', name: 'William Shakespeare', hp: 13, move: 2, attack: 'MELEE', set: 'Slings & Arrows', sidekicks: [{ name: 'Actors', count: 3, hp: 2, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/eSsb82XCOEu2gIjSKE-Xxw__imagepage/img/7fgJVkJ4Qh3r5cWH4d9z1V2bJC0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257668.png', abilityTitle: "IAMBIC PENTAMETER", abilityDescription: "After you attack or defend, add your card to your line. When your line has 10 or more syllables, discard your line. If there are exactly 10 syllables, resolve the completion effect on the last card." },
  { id: 'eredin', name: 'Eredin', hp: 14, move: 2, attack: 'MELEE', set: 'The Witcher – Realms Fall', sidekicks: [{ name: 'Red Riders', count: 4, hp: 1, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/Tn8ZukZMb9ZOYPjB-Cm4iQ__imagepage/img/TLtTLKLGW_2CpT-ySt7z8L76aZs=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7775193.png', abilityTitle: "KING OF THE WILD HUNT", abilityDescription: "While all of your Red Riders are defeated, Eredin is ENRAGED. If Eredin is ENRAGED, add +1 to the value of your combat cards, and your move value is 3." },
  { id: 'philippa', name: 'Philippa', hp: 12, move: 2, attack: 'RANGED', set: 'The Witcher – Realms Fall', sidekicks: [{ name: 'Dijkstra', count: 1, hp: 6, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/y-5o6E3bT9Oaa8j8BnQj6Q__imagepage/img/l2ER3BEshxUc7pOe-mTa75xYfdo=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7775196.png', abilityTitle: "TWO STEPS AHEAD", abilityDescription: "At the end of your turn, you may draw until you have a hand of 4 cards." },
  { id: 'yennefer-triss', name: 'Yennefer & Triss', hp: 14, move: 2, attack: 'RANGED', set: 'The Witcher – Realms Fall', sidekicks: [{ name: 'Yennefer or Triss', count: 1, hp: 6, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/hLHEdyiO7kVqP2R8BnJBZA__imagepage/img/f9kbmXAI9MG7xhtZnCdUFxeZOVM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7775200.png', abilityTitle: "SORCERESS OF VENGERBERG / MERIGOLD THE FEARLESS", abilityDescription: "At the beginning of the game, choose Yennefer or Triss to be your hero. Yennefer: SORCERESS OF VENGERBERG: IMMEDIATELY: If Yennefer is attacking, you may BOOST her attack. (This effect cannot be canceled.) Triss: MERIGOLD THE FEARLESS: After Triss plays a scheme, deal 2 damage to a fighter adjacent to Triss." },
  { id: 'geralt', name: 'Geralt of Rivia', hp: 16, move: 2, attack: 'MELEE', set: 'The Witcher – Steel & Silver', sidekicks: [{ name: 'Dandelion', count: 1, hp: 5, attack: 'RANGED' }], imageUrl: 'https://cf.geekdo-images.com/s9GF0fXi-P4xjKKQd7YpXw__imagepage/img/7NVe-H0Jz55tcrnREK6h_QJdvvM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7775208.png', abilityTitle: "ALWAYS PREPARED", abilityDescription: "At the start of the game, choose your gear. Select a POTION, ARMOR, and SWORD, and shuffle 2 copies of each into your deck." },
  { id: 'muhammad-ali', name: 'Muhammad Ali', hp: 16, move: 3, attack: 'MELEE', set: 'Muhammad Ali vs. Bruce Lee', imageUrl: 'https://cf.geekdo-images.com/4YH7gOTh5Fl4uQD4Fvs4hg__imagepage/img/-hCqy8Iow40l5MPZlMAf1kUJCmg=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7899527.png', abilityTitle: "A BEAUTIFUL SWING", abilityDescription: "Begin the game with your stance on Float Like a Butterfly. After you attack, if you won the combat, change stances. Float Like a Butterfly: You can attack from 2 spaces away. Sting Like a Bee: Add +2 to your attacks." },
  { id: 'bruce-lee-ali', name: 'Bruce Lee', hp: 14, move: 3, attack: 'MELEE', set: 'Muhammad Ali vs. Bruce Lee', imageUrl: 'https://cf.geekdo-images.com/a5Q-X5RMH1gIZGR8aWLBwQ__imagepage/img/LwDJnPvJpVY8xAL2wHb8aY7CxpQ=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7899525.png', abilityTitle: "FLEET OF FOOT", abilityDescription: "At the end of your turn, you may move Bruce Lee 1 space." },
  { id: 'leonardo', name: 'Leonardo', hp: 14, move: 2, attack: 'MELEE', set: 'Unmatched Adventures: Teenage Mutant Ninja Turtles', imageUrl: 'https://cf.geekdo-images.com/VZa1gS0hYjEWLNf8wUGIPA__imagepage/img/LGQOvtY9Vl3Wtu8_xIl_6K8Ckf0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7891993.png', abilityTitle: "TEAM TACTICS", abilityDescription: "At the start of your turn, move any fighter up to 1 space." },
  { id: 'raphael', name: 'Raphael', hp: 16, move: 2, attack: 'MELEE', set: 'Unmatched Adventures: Teenage Mutant Ninja Turtles', sidekicks: [{ name: 'Casey', count: 1, hp: 7, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/c8cF9aWNjUyRSR3jF1SzyA__imagepage/img/W3TIgA8VsJcEJUxgYOpUe4KZeNg=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7891995.png', abilityTitle: "ANGER ISSUES", abilityDescription: "On each of your turns, the first time you lose combat, gain 1 action." },
  { id: 'donatello', name: 'Donatello', hp: 12, move: 2, attack: 'RANGED', set: 'Unmatched Adventures: Teenage Mutant Ninja Turtles', sidekicks: [{ name: 'Metalhead', count: 1, hp: 8, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/M_Cp0GQ7UaC_jdpaTX0BQQ__imagepage/img/T0_iEw7ubIJtkbPLSiNHNJQkKdA=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7891989.png', abilityTitle: "INVENTIVE", abilityDescription: "When you maneuver, you may draw 2 cards instead of 1. If you do, put a card in your hand on the bottom of your deck. After you play an invention, tuck it under this card." },
  { id: 'michelangelo', name: 'Michelangelo', hp: 13, move: 3, attack: 'MELEE', set: 'Unmatched Adventures: Teenage Mutant Ninja Turtles', sidekicks: [{ name: 'April', count: 1, hp: 5, attack: 'MELEE' }], imageUrl: 'https://cf.geekdo-images.com/P0_nzLMBWe3f2zIcLIm-PQ__imagepage/img/hOX4XbjLqtKVCu8iinSp5Sc1Xig=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7891991.png', abilityTitle: "PIZZA PARTY", abilityDescription: "After you attack or scheme, draw 1 card. Your starting and maximum hand size is 3." },
  { id: 'krang', name: 'Krang', hp: 16, move: 1, attack: 'MELEE', set: 'TMNT: Shredder and Krang', imageUrl: '', abilityTitle: "DOOOOOM", abilityDescription: "Krang has 3 doomsday machines. Start with one machine active. After you roll the Die of Ultimate Destruction, you can deactivate an active machine to reroll the die. Add +1 to your move value for each active machine." },
  { id: 'shredder', name: 'Shredder', hp: 15, move: 3, attack: 'MELEE', set: 'TMNT: Shredder and Krang', sidekicks: [{ name: 'Bebop & Rocksteady', count: 1, hp: 7, attack: 'MELEE' }], imageUrl: '', abilityTitle: "MASTER OF THE CLAN", abilityDescription: "At the start of your turn, deploy a Foot soldier to a path adjacent to a friendly fighter. You may attack opposing fighters adjacent to Foot soldiers. If an opponent boosts their maneuver, they may remove any Foot soldiers their hero moves through." },
]

export const MAPS: Map[] = [
  { id: 'mcminnville', name: 'McMinnville OR', set: 'Adventures: Tales to Amaze', minPlayers: 2, maxPlayers: 4, zones: 10, spaces: 42, imageUrl: McMinnvilleOR },
  { id: 'point-pleasant', name: 'Point Pleasant', set: 'Adventures: Tales to Amaze', minPlayers: 2, maxPlayers: 4, zones: 7, spaces: 42, imageUrl: PointPleasant },
  { id: 'marmoreal', name: 'Marmoreal', set: 'Battle of Legends, Volume One', minPlayers: 2, maxPlayers: 4, zones: 8, spaces: 31, imageUrl: Marmoreal },
  { id: 'sarpedon', name: 'Sarpedon', set: 'Battle of Legends, Volume One', minPlayers: 2, maxPlayers: 4, zones: 6, spaces: 38, imageUrl: Sarpedon },
  { id: 'santas-workshop', name: 'Santa\'s Workshop', set: 'Battle of Legends, Volume Three', minPlayers: 2, maxPlayers: 4, zones: 6, spaces: 34 },
  { id: 'venice', name: 'Venice', set: 'Battle of Legends, Volume Three', minPlayers: 2, maxPlayers: 4, zones: 8, spaces: 33 },
  { id: 'hanging-gardens', name: 'Hanging Gardens', set: 'Battle of Legends, Volume Two', minPlayers: 2, maxPlayers: 4, zones: 8, spaces: 33, imageUrl: HangingGardens },
  { id: 'sanctum-sanctorum', name: 'Sanctum Sanctorum', set: 'Brains and Brawn', minPlayers: 2, maxPlayers: 4, zones: 7, spaces: 29, imageUrl: SanctumSantorum },
  { id: 'sunnydale-high', name: 'Sunnydale High', set: 'Buffy the Vampire Slayer', minPlayers: 2, maxPlayers: 4, zones: 6, spaces: 31, imageUrl: SunnydaleHigh },
  { id: 'the-bronze', name: 'The Bronze', set: 'Buffy the Vampire Slayer', minPlayers: 2, maxPlayers: 4, zones: 6, spaces: 35, imageUrl: TheBronze },
  { id: 'baskerville-manor', name: 'Baskerville Manor', set: 'Cobble & Fog', minPlayers: 2, maxPlayers: 4, zones: 7, spaces: 32, imageUrl: BaskervilleManor },
  { id: 'soho', name: 'Soho', set: 'Cobble & Fog', minPlayers: 2, maxPlayers: 4, zones: 7, spaces: 29, imageUrl: Soho },
  { id: 'helicarrier', name: 'Helicarrier', set: 'For King and Country', minPlayers: 2, maxPlayers: 4, zones: 7, spaces: 29, imageUrl: Helicarrier },
  { id: 'hells-kitchen', name: 'Hell\'s Kitchen', set: 'Hell\'s Kitchen', minPlayers: 2, maxPlayers: 4, zones: 7, spaces: 30, imageUrl: HellsKitchenMap },
  { id: 'king-solomons-mine', name: 'King Solomon\'s Mine', set: 'Houdini vs. The Genie', minPlayers: 2, maxPlayers: 2, zones: 7, spaces: 29, imageUrl: KingSolomonsMine },
  { id: 'raptor-paddock', name: 'Raptor Paddock', set: 'Jurassic Park – InGen vs. Raptors', minPlayers: 2, maxPlayers: 2, zones: 6, spaces: 28, imageUrl: RaptorPaddock },
  { id: 't-rex-paddock', name: 'T. Rex Paddock', set: 'Jurassic Park – Sattler vs. T-Rex', minPlayers: 2, maxPlayers: 2, zones: 6, spaces: 26, imageUrl: TRexPaddock },
  { id: 'heorot', name: 'Heorot', set: 'Little Red Riding Hood vs. Beowulf', minPlayers: 2, maxPlayers: 2, zones: 7, spaces: 30, imageUrl: Heorot },
  { id: 'the-raft', name: 'The Raft', set: 'Redemption Row', minPlayers: 2, maxPlayers: 4, zones: 8, spaces: 31, imageUrl: TheRaft },
  { id: 'sherwood-forest', name: 'Sherwood Forest', set: 'Robin Hood vs Bigfoot', minPlayers: 2, maxPlayers: 2, zones: 7, spaces: 30, imageUrl: SherwoodForest },
  { id: 'yukon', name: 'Yukon', set: 'Robin Hood vs Bigfoot', minPlayers: 2, maxPlayers: 2, zones: 7, spaces: 31, imageUrl: Yukon },
  { id: 'globe-theatre', name: 'Globe Theatre', set: 'Slings & Arrows', minPlayers: 2, maxPlayers: 4, zones: 10, spaces: 32, imageUrl: GlobeTheater },
  { id: 'azuchi-castle', name: 'Azuchi Castle', set: 'Sun\'s Origin', minPlayers: 2, maxPlayers: 2, zones: 8, spaces: 31, imageUrl: AzuchiCastle },
  { id: 'navy-pier', name: 'Navy Pier', set: 'Teen Spirit', minPlayers: 2, maxPlayers: 4, zones: 6, spaces: 30, imageUrl: NavyPier },
  { id: 'naglfar', name: 'Naglfar', set: 'The Witcher – Realms Fall', minPlayers: 2, maxPlayers: 4, zones: 7, spaces: 28, imageUrl: Naglfar },
  { id: 'streets-of-novigrad', name: 'Streets of Novigrad', set: 'The Witcher – Realms Fall', minPlayers: 2, maxPlayers: 4, zones: 8, spaces: 34, imageUrl: StreetsOfNovigrad },
  { id: 'fayrlund-forest', name: 'Fayrlund Forest', set: 'The Witcher – Steel & Silver', minPlayers: 2, maxPlayers: 4, zones: 8, spaces: 30, imageUrl: FayrlundForest },
  { id: 'kaer-morhen', name: 'Kaer Morhen', set: 'The Witcher – Steel & Silver', minPlayers: 2, maxPlayers: 4, zones: 8, spaces: 32, imageUrl: KaerMorhen },
  { id: 'technodrome', name: 'Technodrome', set: 'Unmatched Adventures: Teenage Mutant Ninja Turtles', minPlayers: 2, maxPlayers: 4 },
  { id: 'new-york-city', name: 'New York City', set: 'Unmatched Adventures: Teenage Mutant Ninja Turtles', minPlayers: 2, maxPlayers: 4 },
  { id: 'technodrome-sk', name: 'Technodrome', set: 'TMNT: Shredder and Krang', minPlayers: 2, maxPlayers: 4 },
  { id: 'new-york-city-sk', name: 'New York City', set: 'TMNT: Shredder and Krang', minPlayers: 2, maxPlayers: 4 },
]

export function getHeroById(id: string): Hero | undefined {
  const normalizedId = id === 'bruce-lee-ali' ? 'bruce-lee' : id
  return HEROES.find(h => h.id === normalizedId)
}

export function getMapById(id: string): Map | undefined {
  return MAPS.find(m => m.id === id)
}

export function getHeroesBySet(set: string): Hero[] {
  return HEROES.filter(h => h.set === set)
}

export function getMapsBySet(set: string): Map[] {
  return MAPS.filter(m => m.set === set)
}

export function getMapsByPlayerCount(playerCount: number): Map[] {
  return MAPS.filter(m => playerCount >= m.minPlayers && playerCount <= m.maxPlayers)
}

export const ADVENTURE_SETS = ['Adventures: Tales to Amaze', 'Unmatched Adventures: Teenage Mutant Ninja Turtles']

export function getCooperativeMaps(): Map[] {
  return MAPS.filter(m => ADVENTURE_SETS.includes(m.set))
}

export function getSelectableHeroes(): Hero[] {
  return HEROES.filter(h => h.id !== 'bruce-lee-ali')
}
