#!/bin/bash

# Create subdirectories
mkdir -p src/assets/images/heroes
mkdir -p src/assets/images/maps

# Move hero images
mv src/assets/images/Achilles.gif src/assets/images/heroes/
mv src/assets/images/Alice.png src/assets/images/heroes/
mv src/assets/images/Ancient_Leshen.webp src/assets/images/heroes/
mv src/assets/images/Angel.webp src/assets/images/heroes/
mv src/assets/images/Annie_Christmas.webp src/assets/images/heroes/
mv src/assets/images/Beowulf.webp src/assets/images/heroes/
mv src/assets/images/Bigfoot.jpg src/assets/images/heroes/
mv src/assets/images/Black_Panther.webp src/assets/images/heroes/
mv src/assets/images/Black_Widow.webp src/assets/images/heroes/
mv src/assets/images/Blackbeard.webp src/assets/images/heroes/
mv src/assets/images/Bloody_Mary.gif src/assets/images/heroes/
mv src/assets/images/Bruce_Lee.jpg src/assets/images/heroes/
mv src/assets/images/Buffy.webp src/assets/images/heroes/
mv src/assets/images/Bullseye.webp src/assets/images/heroes/
mv src/assets/images/Chupacabra.webp src/assets/images/heroes/
mv src/assets/images/Ciri.webp src/assets/images/heroes/
mv src/assets/images/Cloak_Dagger.webp src/assets/images/heroes/
mv src/assets/images/Daredevil.webp src/assets/images/heroes/
mv src/assets/images/Deadpool.webp src/assets/images/heroes/
mv src/assets/images/Doctor_Strange.webp src/assets/images/heroes/
mv src/assets/images/Donatello.webp src/assets/images/heroes/
mv src/assets/images/Dr._Sattler.webp src/assets/images/heroes/
mv src/assets/images/Dr_Jeykll.png src/assets/images/heroes/
mv src/assets/images/Dr_Jill_Trent.webp src/assets/images/heroes/
mv src/assets/images/Dracula.png src/assets/images/heroes/
mv src/assets/images/Elektra.webp src/assets/images/heroes/
mv src/assets/images/Eredin.webp src/assets/images/heroes/
mv src/assets/images/Geralt.webp src/assets/images/heroes/
mv src/assets/images/Ghost_Rider.webp src/assets/images/heroes/
mv src/assets/images/Golden_Bat.webp src/assets/images/heroes/
mv src/assets/images/Hamlet.webp src/assets/images/heroes/
mv src/assets/images/Houdini.webp src/assets/images/heroes/
mv src/assets/images/Invisible_Man.png src/assets/images/heroes/
mv src/assets/images/King_Arthur.png src/assets/images/heroes/
mv src/assets/images/Leonardo.webp src/assets/images/heroes/
mv src/assets/images/Loki.webp src/assets/images/heroes/
mv src/assets/images/Luke_Cage.webp src/assets/images/heroes/
mv src/assets/images/Medusa.png src/assets/images/heroes/
mv src/assets/images/Michaelangelo.webp src/assets/images/heroes/
mv src/assets/images/Moon_Knight.webp src/assets/images/heroes/
mv src/assets/images/Ms_Marvel.webp src/assets/images/heroes/
mv src/assets/images/Nikola_Tesla.webp src/assets/images/heroes/
mv src/assets/images/Oda_Nobunaga.webp src/assets/images/heroes/
mv src/assets/images/Pandora.webp src/assets/images/heroes/
mv src/assets/images/Philippa.webp src/assets/images/heroes/
mv src/assets/images/Raphael.webp src/assets/images/heroes/
mv src/assets/images/Raptors.webp src/assets/images/heroes/
mv src/assets/images/Red_Riding_Hood.webp src/assets/images/heroes/
mv src/assets/images/Robert_Muldoon.webp src/assets/images/heroes/
mv src/assets/images/Robin_Hood.jpg src/assets/images/heroes/
mv src/assets/images/Shakespeare.webp src/assets/images/heroes/
mv src/assets/images/She-Hulk.webp src/assets/images/heroes/
mv src/assets/images/Sherlock_Holmes.png src/assets/images/heroes/
mv src/assets/images/Sinbad.png src/assets/images/heroes/
mv src/assets/images/Spider-Man.webp src/assets/images/heroes/
mv src/assets/images/Spike.webp src/assets/images/heroes/
mv src/assets/images/Squirrel_Girl.webp src/assets/images/heroes/
mv src/assets/images/Sun_Wukong.jpg src/assets/images/heroes/
mv src/assets/images/T_Rex.webp src/assets/images/heroes/
mv src/assets/images/The_Genie.webp src/assets/images/heroes/
mv src/assets/images/The_Wayward_Sisters.webp src/assets/images/heroes/
mv src/assets/images/Titania.webp src/assets/images/heroes/
mv src/assets/images/Tomoe_Gozen.webp src/assets/images/heroes/
mv src/assets/images/Triss.webp src/assets/images/heroes/
mv src/assets/images/Willow.webp src/assets/images/heroes/
mv src/assets/images/Winter_Soldier.webp src/assets/images/heroes/
mv src/assets/images/Yennefer.webp src/assets/images/heroes/
mv src/assets/images/Yennenga.jpg src/assets/images/heroes/

# Move map images
mv src/assets/images/Azuchi_Castle.webp src/assets/images/maps/
mv src/assets/images/Baskerville_Manor.webp src/assets/images/maps/
mv src/assets/images/Fayrlund_Forest.webp src/assets/images/maps/
mv src/assets/images/Globe_Theater.webp src/assets/images/maps/
mv src/assets/images/Hanging_Gardens.webp src/assets/images/maps/
mv src/assets/images/Helicarrier.webp src/assets/images/maps/
mv "src/assets/images/Hell's_Kitchen.webp" src/assets/images/maps/
mv src/assets/images/Heorot.webp src/assets/images/maps/
mv src/assets/images/Kaer_Morhen.webp src/assets/images/maps/
mv "src/assets/images/King_Solomon's_Mine.webp" src/assets/images/maps/
mv src/assets/images/Marmoreal.webp src/assets/images/maps/
mv src/assets/images/McMinnville_OR.webp src/assets/images/maps/
mv src/assets/images/Naglfar.webp src/assets/images/maps/
mv src/assets/images/Navy_Pier.webp src/assets/images/maps/
mv src/assets/images/Point_Pleasant.webp src/assets/images/maps/
mv src/assets/images/Raptor_Paddock.webp src/assets/images/maps/
mv src/assets/images/Sanctum_Santorum.webp src/assets/images/maps/
mv src/assets/images/Sarpedon.webp src/assets/images/maps/
mv src/assets/images/Sherwood_Forest.webp src/assets/images/maps/
mv src/assets/images/Soho.webp src/assets/images/maps/
mv src/assets/images/Streets_of_Novigrad.webp src/assets/images/maps/
mv src/assets/images/Sunnydale_High.webp src/assets/images/maps/
mv src/assets/images/The_Bronze.webp src/assets/images/maps/
mv src/assets/images/The_Raft.webp src/assets/images/maps/
mv src/assets/images/T_Rex_Paddock.webp src/assets/images/maps/
mv src/assets/images/Yukon.webp src/assets/images/maps/

echo "Images organized successfully!"
