#!/bin/bash

# Script to organize images into heroes and maps subdirectories

cd "$(dirname "$0")/src/assets/images"

# Move hero images
echo "Moving hero images..."
mv Achilles.gif heroes/ 2>/dev/null
mv Alice.png heroes/ 2>/dev/null
mv Ancient_Leshen.webp heroes/ 2>/dev/null
mv Angel.webp heroes/ 2>/dev/null
mv Annie_Christmas.webp heroes/ 2>/dev/null
mv Beowulf.webp heroes/ 2>/dev/null
mv Bigfoot.jpg heroes/ 2>/dev/null
mv Black_Panther.webp heroes/ 2>/dev/null
mv Black_Widow.webp heroes/ 2>/dev/null
mv Blackbeard.png heroes/ 2>/dev/null
mv Blackbeard.webp heroes/ 2>/dev/null
mv Bloody_Mary.gif heroes/ 2>/dev/null
mv Bruce_Lee.jpg heroes/ 2>/dev/null
mv Buffy.webp heroes/ 2>/dev/null
mv Bullseye.webp heroes/ 2>/dev/null
mv Chupacabra.png heroes/ 2>/dev/null
mv Chupacabra.webp heroes/ 2>/dev/null
mv Ciri.webp heroes/ 2>/dev/null
mv Cloak_Dagger.webp heroes/ 2>/dev/null
mv Daredevil.webp heroes/ 2>/dev/null
mv Deadpool.png heroes/ 2>/dev/null
mv Deadpool.webp heroes/ 2>/dev/null
mv Doctor_Strange.webp heroes/ 2>/dev/null
mv Donatello.webp heroes/ 2>/dev/null
mv Dr._Sattler.webp heroes/ 2>/dev/null
mv Dr_Jeykll.png heroes/ 2>/dev/null
mv Dr_Jill_Trent.webp heroes/ 2>/dev/null
mv Dracula.png heroes/ 2>/dev/null
mv Elektra.webp heroes/ 2>/dev/null
mv Eredin.webp heroes/ 2>/dev/null
mv Geralt.webp heroes/ 2>/dev/null
mv Ghost_Rider.webp heroes/ 2>/dev/null
mv Golden_Bat.webp heroes/ 2>/dev/null
mv Hamlet.webp heroes/ 2>/dev/null
mv Houdini.webp heroes/ 2>/dev/null
mv Invisible_Man.png heroes/ 2>/dev/null
mv King_Arthur.png heroes/ 2>/dev/null
mv Leonardo.webp heroes/ 2>/dev/null
mv Loki.png heroes/ 2>/dev/null
mv Loki.webp heroes/ 2>/dev/null
mv Luke_Cage.webp heroes/ 2>/dev/null
mv Medusa.png heroes/ 2>/dev/null
mv Michaelangelo.webp heroes/ 2>/dev/null
mv Moon_Knight.webp heroes/ 2>/dev/null
mv Ms_Marvel.webp heroes/ 2>/dev/null
mv Nikola_Tesla.webp heroes/ 2>/dev/null
mv Oda_Nobunaga.webp heroes/ 2>/dev/null
mv Pandora.png heroes/ 2>/dev/null
mv Pandora.webp heroes/ 2>/dev/null
mv Philippa.webp heroes/ 2>/dev/null
mv Raphael.webp heroes/ 2>/dev/null
mv Raptors.webp heroes/ 2>/dev/null
mv Red_Riding_Hood.webp heroes/ 2>/dev/null
mv Robert_Muldoon.webp heroes/ 2>/dev/null
mv Robin_Hood.jpg heroes/ 2>/dev/null
mv Shakespeare.webp heroes/ 2>/dev/null
mv She-Hulk.webp heroes/ 2>/dev/null
mv Sherlock_Holmes.png heroes/ 2>/dev/null
mv Sinbad.png heroes/ 2>/dev/null
mv Spider-Man.webp heroes/ 2>/dev/null
mv Spike.webp heroes/ 2>/dev/null
mv Squirrel_Girl.webp heroes/ 2>/dev/null
mv Sun_Wukong.jpg heroes/ 2>/dev/null
mv T_Rex.webp heroes/ 2>/dev/null
mv The_Genie.webp heroes/ 2>/dev/null
mv The_Wayward_Sisters.webp heroes/ 2>/dev/null
mv Titania.webp heroes/ 2>/dev/null
mv Tomoe_Gozen.webp heroes/ 2>/dev/null
mv Triss.webp heroes/ 2>/dev/null
mv Willow.webp heroes/ 2>/dev/null
mv Winter_Soldier.webp heroes/ 2>/dev/null
mv Yennefer.webp heroes/ 2>/dev/null
mv Yennenga.jpg heroes/ 2>/dev/null

# Move map images
echo "Moving map images..."
mv Azuchi_Castle.webp maps/ 2>/dev/null
mv Baskerville_Manor.webp maps/ 2>/dev/null
mv Fayrlund_Forest.webp maps/ 2>/dev/null
mv Globe_Theater.webp maps/ 2>/dev/null
mv Hanging_Gardens.webp maps/ 2>/dev/null
mv Helicarrier.webp maps/ 2>/dev/null
mv "Hell's_Kitchen.webp" maps/ 2>/dev/null
mv Heorot.webp maps/ 2>/dev/null
mv Kaer_Morhen.webp maps/ 2>/dev/null
mv "King_Solomon's_Mine.webp" maps/ 2>/dev/null
mv Marmoreal.webp maps/ 2>/dev/null
mv McMinnville_OR.webp maps/ 2>/dev/null
mv Naglfar.webp maps/ 2>/dev/null
mv Navy_Pier.webp maps/ 2>/dev/null
mv Point_Pleasant.webp maps/ 2>/dev/null
mv Raptor_Paddock.webp maps/ 2>/dev/null
mv Sanctum_Santorum.webp maps/ 2>/dev/null
mv Sarpedon.webp maps/ 2>/dev/null
mv Sherwood_Forest.webp maps/ 2>/dev/null
mv Soho.webp maps/ 2>/dev/null
mv Streets_of_Novigrad.webp maps/ 2>/dev/null
mv Sunnydale_High.webp maps/ 2>/dev/null
mv The_Bronze.webp maps/ 2>/dev/null
mv The_Raft.webp maps/ 2>/dev/null
mv T_Rex_Paddock.webp maps/ 2>/dev/null
mv Yukon.webp maps/ 2>/dev/null

echo "Done! Images have been organized into heroes/ and maps/ subdirectories."
